Install pigz on CI workflow
Recent runner image (Image: ubuntu-22.04, Version: 20230821.1.0?) does not have pigz.

```
Run docker save minimum2scp/baseimage-bookworm:latest | pigz -c - > /tmp/baseimage-bookworm.tar.gz
/home/runner/work/_temp/ab82cfe4-3692-47b7-a9ec-e048e85f5bb2.sh: line 1: pigz: command not found
Error: Process completed with exit code 127.
```