norikra: updated jruby to 9.2.11.1
Fixes build error:

```
+ bash -l -c RBENV_VERSION=jruby-9.1.5.0 gem install norikra
unsupported Java version "11", defaulting to 1.7
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jruby.util.io.FilenoUtil to method sun.nio.ch.SelChImpl.getFD()
WARNING: Please consider reporting this to the maintainers of org.jruby.util.io.FilenoUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
io/console on JRuby shells out to stty for most operations
Successfully installed erubis-2.7.0
Successfully installed rack-2.2.3
Successfully installed tilt-2.0.10
Successfully installed rack-protection-2.0.8.1
Successfully installed ruby2_keywords-0.0.2
Successfully installed mustermann-1.1.1
Successfully installed sinatra-2.0.8.1
Successfully installed backports-3.18.0
Successfully installed multi_json-1.14.1
Successfully installed sinatra-contrib-2.0.8.1
Successfully installed ltsv-0.1.2
Successfully installed thor-1.0.1
Successfully installed httpclient-2.8.3
Successfully installed hitimes-2.0.0
Successfully installed timers-4.0.4
Successfully installed celluloid-0.16.0
Successfully installed msgpack-1.3.3-java
Successfully installed msgpack-rpc-over-http-0.1.0
Successfully installed norikra-client-1.4.0
ERROR:  Error installing norikra:
	childprocess requires Ruby version >= 2.4.0.
run-parts: /tmp/build/norikra/scripts/02-rbenv exited with return code 1
```