fluentd-ui: install libssl1.0-dev (openssl 1.0.x) instead of libssl-dev (openssl 1.1.0)
puma extention build failed with openssl 1.1.0:

```
Installing puma 2.11.1 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /opt/fluentd-ui/vendor/bundle/ruby/2.3.0/gems/puma-2.11.1/ext/puma_http11
/usr/bin/ruby2.3 -r ./siteconf20161103-1192-52b9o8.rb extconf.rb
checking for BIO_read() in -lcrypto... yes
checking for SSL_CTX_new() in -lssl... yes
creating Makefile

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /opt/fluentd-ui/vendor/bundle/ruby/2.3.0/extensions/x86_64-linux/2.3.0/puma-2.11.1/mkmf.log

current directory: /opt/fluentd-ui/vendor/bundle/ruby/2.3.0/gems/puma-2.11.1/ext/puma_http11
make "DESTDIR=" clean

current directory: /opt/fluentd-ui/vendor/bundle/ruby/2.3.0/gems/puma-2.11.1/ext/puma_http11
make "DESTDIR="
compiling http11_parser.c
compiling io_buffer.c
compiling mini_ssl.c
In file included from mini_ssl.c:3:0:
/usr/include/ruby-2.3.0/ruby/backward/rubyio.h:2:2: warning: #warning use "ruby/io.h" instead of "rubyio.h" [-Wcpp]
 #warning use "ruby/io.h" instead of "rubyio.h"
  ^~~~~~~
mini_ssl.c: In function 'get_dh1024':
mini_ssl.c:65:5: error: dereferencing pointer to incomplete type 'DH {aka struct dh_st}'
   dh->p = BN_bin2bn(dh1024_p, sizeof(dh1024_p), NULL);
     ^~
mini_ssl.c: In function 'engine_init_client':
mini_ssl.c:124:3: warning: 'DTLSv1_method' is deprecated [-Wdeprecated-declarations]
   conn->ctx = SSL_CTX_new(DTLSv1_method());
   ^~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from mini_ssl.c:5:
/usr/include/openssl/ssl.h:1614:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *DTLSv1_method(void)) /* DTLSv1.0 */
 ^
Makefile:239: recipe for target 'mini_ssl.o' failed
make: *** [mini_ssl.o] Error 1

make failed, exit code 2

Gem files will remain installed in /opt/fluentd-ui/vendor/bundle/ruby/2.3.0/gems/puma-2.11.1 for inspection.
Results logged to /opt/fluentd-ui/vendor/bundle/ruby/2.3.0/extensions/x86_64-linux/2.3.0/puma-2.11.1/gem_make.out

An error occurred while installing puma (2.11.1), and Bundler cannot continue.
Make sure that `gem install puma -v '2.11.1'` succeeds before bundling.
```