tdiary: Install libidn11-dev to fix bundle install error
```
+ bash -l -c bundle install
Fetching gem metadata from https://rubygems.org/........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 12.3.1
Using public_suffix 3.0.2
Using bundler 1.16.2
Using mini_mime 1.0.0
Using mini_portile2 2.3.0
Using rack 2.0.5
Using ffi 1.9.23
Using concurrent-ruby 1.0.5
Using json 2.1.0
Using docile 1.1.5
Using simplecov-html 0.10.2
Using tins 1.16.3
Using thor 0.19.4
Using diff-lcs 1.3
Using multipart-post 2.0.0
Using fastimage 2.1.3
Using hikidoc 0.1.0
Using jasmine-core 2.99.2
Using phantomjs 2.1.1.0
Fetching idn-ruby 0.1.0
Using pit 0.0.7
Using power_assert 1.1.1
Fetching mime-types-data 3.2016.0521
Fetching rdtool 0.6.38
Installing idn-ruby 0.1.0 with native extensions
Installing mime-types-data 3.2016.0521
Using redcarpet 3.4.0
Using rspec-support 3.7.1
Using rubyzip 1.2.1
Using sequel 5.9.0
Using sqlite3 1.3.13
Fetching unf_ext 0.0.7.5
Installing rdtool 0.6.38
Installing unf_ext 0.0.7.5 with native extensions
Using nokogiri 1.8.2
Using rack-test 1.0.0
Using childprocess 0.9.0
Fetching i18n 1.0.1
Installing i18n 1.0.1
Using sprockets 3.7.1
Using simplecov 0.14.1
Using term-ansicolor 1.6.0
Using emot 0.0.4
Using faraday 0.15.1
Using addressable 2.5.2
Using jasmine 2.99.0
Using mail 2.7.0
Using test-unit 3.2.8
Fetching mime-types 3.1
Installing mime-types 3.1
Using rspec-core 3.7.1
Using rspec-expectations 3.7.0
Using rspec-mocks 3.7.0
Using xpath 3.1.0
Using racksh 1.0.0
Using selenium-webdriver 3.12.0
Using tdiary-style-rd 0.0.3 from source at `../tdiary-style-rd`
Using coveralls 0.8.21
Using launchy 2.4.3
Using sawyer 0.8.1
Using tdiary 5.0.8 from source at `.`
Using capybara 3.2.1
Fetching pushbullet_ruby 1.1.4
Using rspec 3.7.0
Fetching ruby-enum 0.7.2
Using octokit 4.9.0
Fetching unf 0.1.4
Installing pushbullet_ruby 1.1.4
Installing ruby-enum 0.7.2
Installing unf 0.1.4
Fetching commonmarker 0.17.9
Using tdiary-contrib 5.0.8 from source at `../tdiary-contrib`
Installing commonmarker 0.17.9 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/home/debian/go/src/github.com/tdiary/tdiary-core/vendor/bundle/ruby/2.5.0/gems/idn-ruby-0.1.0/ext
/opt/rbenv/versions/2.5.1/bin/ruby -r ./siteconf20180610-11470-g9dvht.rb
extconf.rb
checking for -lidn... no
ERROR: could not find idn library!

  Please install the GNU IDN library or alternatively specify at least one
  of the following options if the library can only be found in a non-standard
  location:
    --with-idn-dir=/path/to/non/standard/location
        or
    --with-idn-lib=/path/to/non/standard/location/lib
    --with-idn-include=/path/to/non/standard/location/include

*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/rbenv/versions/2.5.1/bin/$(RUBY_BASE_NAME)
	--with-idn-dir
	--without-idn-dir
	--with-idn-include
	--without-idn-include=${idn-dir}/include
	--with-idn-lib
	--without-idn-lib=${idn-dir}/lib
	--with-idnlib
	--without-idnlib

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

/home/debian/go/src/github.com/tdiary/tdiary-core/vendor/bundle/ruby/2.5.0/extensions/x86_64-linux/2.5.0-static/idn-ruby-0.1.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
/home/debian/go/src/github.com/tdiary/tdiary-core/vendor/bundle/ruby/2.5.0/gems/idn-ruby-0.1.0
for inspection.
Results logged to
/home/debian/go/src/github.com/tdiary/tdiary-core/vendor/bundle/ruby/2.5.0/extensions/x86_64-linux/2.5.0-static/idn-ruby-0.1.0/gem_make.out

An error occurred while installing idn-ruby (0.1.0), and Bundler cannot
continue.
Make sure that `gem install idn-ruby -v '0.1.0' --source
'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  tdiary-style-gfm was resolved to 1.1.0, which depends on
    twitter-text was resolved to 2.1.0, which depends on
      idn-ruby
run-parts: /tmp/build/tdiary/scripts/01-setup exited with return code 5
The command '/bin/sh -c run-parts --report --exit-on-error /tmp/build/tdiary/scripts && rm -rfv /tmp/build' returned a non-zero code: 1
Exited with code 1
```